---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ansible-test
    image: "geerlingguy/ansible:latest"
    volumes:
      - /home/dhaskin/madeup.log:/var/log/ultradns-quiz-madeup.log:ro
    privileged: true
    cgroupns_mode: "host"

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    group_vars:
      all:
        ansible_connection: docker
        ansible_user: root
    host_vars:
      ansible-test: {}

verifier:
  name: ansible
